### PR TITLE
Isiaq/footer section

### PR DESCRIPTION
**Pull request by DevBigEazi**
@Khadeeejah I'm done with this https://github.com/Khadeeejah/celo-africa-dao/issues/9

### CODE REVIEW

**Comment by Khadeeejah** [comment]
Hi currently under review

**Comment by DevBigEazi** [comment]
Looking forward to your feedback

**Comment by Khadeeejah** [comment]
I was unable to run your code on my local machine as it failed to compile, please check your layout and let me know if you need any assistance

**Comment by DevBigEazi** [comment]
The code is working perfectly on my local machine before i pushed it here....

**Comment by Khadeeejah** [comment]
Your code won't comipile or run well if you are attempting to export "metadata" from a component marked with "use client", 

So comment that part out or remove it and update your pr

**Comment by DevBigEazi** [comment]
ok done....pls check it out

**Pull request closed without merging**
