### PR TITLE
Navbar with desktop view, and mobile views

### PR DESCRIPTION
**Pull request by Mentor-Ntech**
please kindly review again # @Khadeeejah

### CODE REVIEW

**Comment by Khadeeejah** [comment]
hello, 

1 Please do a rebase, or a merge to resolve conflict.

2 You will see a component folder, create a folder "Navbar" and create another file `"Navbar.js `not `Navbar.jsx`

3 The colour of your navbar is different from the design
Screenshot 2023-07-18 at 07 26 57

4 Please use the font size and font that is provided on figma and also adjust your padding and margins

Screenshot 2023-07-18 at 07 27 44

**Comment by Khadeeejah** [comment]
Lastly, do not close this PR, if you do not know howw to update a pr please watch this [video](https://www.youtube.com/watch?v=Hi2mRlmasCU)

**Comment by Khadeeejah** [comment]
Hi please resolve all conflicts on this branch

**Comment by Khadeeejah** [comment]
> hello,
> 
> 1 Please do a rebase, or a merge to resolve conflict.
> 
> 2 You will see a component folder, create a folder "Navbar" and create another file `"Navbar.js `not `Navbar.jsx`
> 
> 3 The colour of your navbar is different from the design Screenshot 2023-07-18 at 07 26 57
> 
> 4 Please use the font size and font that is provided on figma and also adjust your padding and margins
> 
> Screenshot 2023-07-18 at 07 27 44

Also follow the instructions here

**Comment by Mentor-Ntech** [comment]
Good day @Khadeeejah ...kindly check pls

**Comment by Mentor-Ntech** [comment]
Hi @Khadeeejah, pls check now. Thanks

**Comment by Khadeeejah** [comment]
Hi, if you look at the design, the navbar doesnt have a border at the bottom, please take that out
Screenshot 2023-08-03 at 23 36 44

**Comment by Khadeeejah** [comment]
Hi, i can still see it 
Screenshot 2023-08-10 at 12 28 38

**Comment by Mentor-Ntech** [comment]
Hello, I hope you're having a good day. I don't quite comprehend your message because there's no border initially. What indicates the position is fixed, unless you're suggesting I remove the position fixed and use position sticky? Thanks

**Comment by Mentor-Ntech** [comment]
In my previous correction, I had removed the box-shadow. Upon checking the main company website, I noticed that they also utilize the position fixed.

**Comment by Mentor-Ntech** [comment]
Screenshot 2023-08-11 111252
Screenshot 2023-08-11 130154

Have correct this you can check the picture to verify

**Pull request merged**
