### PR TITLE
Soliu/faq section

### PR DESCRIPTION
**Pull request by codesoliu**
now on staging @Khadeeejah

### CODE REVIEW

**Comment by Khadeeejah** [comment]
hello,

1 Please do a rebase, or a merge to resolve conflict.

2 You will see a component folder, create a folder `"FAQS"` and create another file "`Faqs.js `

3 Your design is not the same with what was provided on figma, Please follow the style guide such as colours, font , width, height and font size.

4 make your design mobile responsive

4 Lastly, do not close this PR, if you do not know howw to update a pr please watch this [video](https://www.youtube.com/watch?v=Hi2mRlmasCU)

**Comment by codesoliu** [comment]
check it please @Khadeeejah

**Comment by Khadeeejah** [comment]
Hello just a little update, please increase the font size and also take note of this margin from the design.


Screenshot 2023-07-20 at 05 15 40

**Comment by Khadeeejah** [comment]
Hi welldone, i would merge this pr. please pick  another issue

**Pull request merged**
