### PR TITLE
Hero section designed

### PR DESCRIPTION
**Pull request by Mentor-Ntech**
@Khadeeejah kindly review. Thanks.

### CODE REVIEW

**Comment by Khadeeejah** [comment]
hello, the button is too big, also reduce the with of the text has it has taken so much space from the section.
Screenshot 2023-08-20 at 09 43 44

The illustration is too small, please follow the design guide. thank you

**Comment by Mentor-Ntech** [comment]
Hello good day, @Khadeeejah the text, button and illustration have been corrected

**Comment by Khadeeejah** [comment]
Hi please do a quick pull or a rebase, i just merged a new pr

**Comment by Khadeeejah** [comment]
Also the width of the text is too big, and the hero image needs to be big too, im happy to jump on a call with you to review this properly

**Comment by Khadeeejah** [comment]
Screenshot 2023-08-21 at 13 05 15


this is how its meant to look btw

**Comment by Mentor-Ntech** [comment]
The width of the Text and illustration correction done @Khadeeejah have

**Pull request merged**
