### PR TITLE
Isiaq/footer section

### PR DESCRIPTION
**Pull request by DevBigEazi**
Done #9 @Khadeeejah

### CODE REVIEW

**Comment by Khadeeejah** [comment]
Great Job @DevBigEazi please make these adjustment and let me know when you are done. please do not close this pr, if you are unsure about updating your PR please let me know or check this [Video](https://www.youtube.com/watch?v=Hi2mRlmasCU)

**Comment by Khadeeejah** [comment]
Lastly import the image as an SVG for better quality

**Comment by DevBigEazi** [comment]
Thank you for the nice feedback and guidance @Khadeeejah . I have updated the pr.

**Comment by Khadeeejah** [comment]
Screenshot 2023-07-18 at 07 18 11
Screenshot 2023-07-18 at 07 18 45


please make sure your design is the exact replica of what we have on figma for small screens

**Pull request merged**
